# templates/deployment-service2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-service2
spec:
  replicas: {{ .Values.service2.replicaCount }}
  selector:
    matchLabels:
      app: nodejs-service2
  template:
    metadata:
      labels:
        app: nodejs-service2
    spec:
      containers:
        - name: nodejs-service2
          image: "{{ .Values.service2.image.repository }}:{{ .Values.service2.image.tag }}"
          imagePullPolicy: {{ .Values.service2.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service2.port }}
