# templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-service1
spec:
  rules:
    - host: {{ .Values.ingress.service1.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-service1
                port:
                  number: 80
{{- end }}

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-service2
spec:
  rules:
    - host: {{ .Values.ingress.service2.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-service2
                port:
                  number: 80
{{- end }}
