# templates/service-service2.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service2
spec:
  selector:
    app: nodejs-service2
  ports:
    - protocol: TCP
      port: {{ .Values.service2.service.port }}
      targetPort: {{ .Values.service2.port }}
